#!/bin/bash

HOSTCA=${1:-hostca}

CAPUB="$(ssh ${HOSTCA} cat /etc/ssh/host-ca.pub)" || {
	echo Failed to get CA public key >&2
	exit 1
}
if [ ! -f /etc/ssh/ssh_known_hosts ]; then
	# sed can only append to files that have at least one line.
	sudo sh -c 'echo >>/etc/ssh/ssh_known_hosts'
fi
sudo sed -i.bak -e "
/@cert-authority . $(echo $CAPUB | sed 's@/@.@g')/d
$ a@cert-authority * ${CAPUB}
" /etc/ssh/ssh_known_hosts
